function PrivacyPolicy() {
  return (
    <div id="policy" className="privacy-policy-container p-8">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
      <p className="mb-4 text-sm">Updated at October 5th, 2024</p>
      <p className="mb-4">
        lusiboi entertainment (“we,” “our,” or “us”) is committed to protecting
        your privacy. This Privacy Policy explains how your personal information
        is collected, used, and disclosed by lusiboi entertainment. This Privacy
        Policy applies to our website, and its associated subdomains
        (collectively, our “Service”) alongside our application, lusiboi
        entertainment. By accessing or using our Service, you signify that you
        have read, understood, and agree to our collection, storage, use, and
        disclosure of your personal information as described in this Privacy
        Policy and our Terms of Service.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Definitions and key terms</h2>
      <ul className="list-disc list-inside mb-4">
        <li>
          <strong>Cookie:</strong> small amount of data generated by a website
          and saved by your web browser.
        </li>
        <li>
          <strong>Company:</strong> refers to Lusiboi Entertainment.
        </li>
        <li>
          <strong>Country:</strong> Nigeria, where Lusiboi Entertainment is
          based.
        </li>
        <li>
          <strong>Customer:</strong> Refers to the person that signs up to use
          Lusiboi Entertainment services.
        </li>
        <li>
          <strong>Device:</strong> Any internet connected device used to access
          Lusiboi Entertainment services.
        </li>
        <li>
          <strong>IP address:</strong> A number assigned to devices connected to
          the Internet.
        </li>
        <li>
          <strong>Personnel:</strong> Refers to employees or contractors of
          Lusiboi Entertainment.
        </li>
        <li>
          <strong>Personal Data:</strong> Information that identifies a person.
        </li>
        <li>
          <strong>Service:</strong> The service provided by Lusiboi
          Entertainment.
        </li>
        <li>
          <strong>Third-party service:</strong> Advertisers, partners, or others
          providing content or services.
        </li>
        <li>
          <strong>Website:</strong> Lusiboi Entertainment&apos;s website,
          accessible at www.lusiboientertainment.com.
        </li>
        <li>
          <strong>You:</strong> A person or entity using the services of Lusiboi
          Entertainment.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">
        What Information Do We Collect?
      </h2>
      <p className="mb-4">
        We collect information when you visit our website, register, place an
        order, subscribe to our newsletter, respond to a survey, or fill out a
        form. The information collected includes:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Name / Username</li>
        <li>Phone Numbers</li>
        <li>Email Addresses</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">
        When does lusiboi entertainment use end user information from third
        parties?
      </h2>
      <p className="mb-4">
        lusiboi entertainment collects End User Data necessary to provide
        services to our customers. Users may voluntarily provide information
        from social media websites. We may collect this publicly available
        information.
      </p>

      {/* Add more sections similarly based on the content of the policy document */}
      <h2 className="text-2xl font-semibold mb-4">
        When does lusiboi entertainment use customer information from third
        parties?
      </h2>
      <p className="mb-4">
        We receive some information from the third parties when you contact us.
        For example, when you submit your email address to us to show interest
        in becoming a lusiboi entertainment customer, we receive information
        from a third party that provides automated fraud detection services to
        lusiboi entertainment. We also occasionally collect information that is
        made publicly available on social media websites. You can control how
        much of your information social media websites make public by visiting
        these websites and changing your privacy settings.
      </p>

      <h2 className="text-2xl font-semibold mb-4">
        Do we share the information we collect with third parties?
      </h2>
      <p className="mb-4">
        We may share the information that we collect, both personal and
        non-personal, with third parties such as advertisers, contest sponsors,
        promotional and marketing partners, and others who provide our content
        or whose products or services we think may interest you. We may also
        share it with our current and future affiliated companies and business
        partners, and if we are involved in a merger, asset sale or other
        business reorganization, we may also share or transfer your personal and
        non-personal information to our successors-in-interest.
      </p>

      <p className="mb-4">
        We may engage trusted third party service providers to perform functions
        and provide services to us, such as hosting and maintaining our servers
        and the website, database storage and management, e-mail management,
        storage marketing, credit card processing, customer service and
        fulfilling orders for products and services you may purchase through the
        website. We will likely share your personal information, and possibly
        some non-personal information, with these third parties to enable them
        to perform these services for us and for you.
      </p>

      <p className="mb-4">
        We may share portions of our log file data, including IP addresses, for
        analytics purposes with third parties such as web analytics partners,
        application developers, and ad networks. If your IP address is shared,
        it may be used to estimate general location and other technographics
        such as connection speed, whether you have visited the website in a
        shared location, and type of the device used to visit the website. They
        may aggregate information about our advertising and what you see on the
        website and then provide auditing, research and reporting for us and our
        advertisers.
      </p>

      <p className="mb-4">
        We may also disclose personal and non-personal information about you to
        government or law enforcement officials or private parties as we, in our
        sole discretion, believe necessary or appropriate in order to respond to
        claims, legal process (including subpoenas), to protect our rights and
        interests or those of a third party, the safety of the public or any
        person, to prevent or stop any illegal, unethical, or legally actionable
        activity, or to otherwise comply with applicable court orders, laws,
        rules and regulations.
      </p>

      <h2 className="text-2xl font-semibold mb-4">
        Where and when is information collected from customers and end users?
      </h2>
      <p className="mb-4">
        lusiboi entertainment will collect personal information that you submit
        to us. We may also receive personal information about you from third
        parties as described above.
      </p>

      <ul className="list-disc list-inside mb-4">
        <p>
          Any of the information we collect from you may be used in one of the
          following ways:
        </p>
        <li>
          To personalize your experience (your information helps us to better
          respond to your individual needs)
        </li>
        <li>
          To improve our website (we continually strive to improve our website
          offerings based on the information and feedback we receive from you)
        </li>
        <li>
          To improve customer service (your information helps us to more
          effectively respond to your customer service requests and support
          needs)
        </li>
        <li>To process transactions</li>
        <li>
          To administer a contest, promotion, survey or other site feature
        </li>
        <li>To send periodic emails</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">
        How Do We Use Your Email Address?{" "}
      </h2>
      <p className="mb-4">
        By submitting your email address on this website, you agree to receive
        emails from us. You can cancel your participation in any of these email
        lists at any time by clicking on the opt-out link or other unsubscribe
        option that is included in the respective email. We only send emails to
        people who have authorized us to contact them, either directly, or
        through a third party. We do not send unsolicited commercial emails,
        because we hate spam as much as you do. By submitting your email
        address, you also agree to allow us to use your email address for
        customer audience targeting on sites like Facebook, where we display
        custom advertising to specific people who have opted-in to receive
        communications from us. Email addresses submitted only through the order
        processing page will be used for the sole purpose of sending you
        information and updates pertaining to your order. If, however, you have
        provided the same email to us through another method, we may use it for
        any of the purposes stated in this Policy. Note: If at any time you
        would like to unsubscribe page 4/8 from receiving future emails, we
        include detailed unsubscribe instructions at the bottom of each email.
      </p>

      <h2 className="text-2xl font-semibold mb-4">
        How Long Do We Keep Your Information?
      </h2>
      <p className="mb-4">
        We keep your information only so long as we need it to provide lusiboi
        entertainment to you and fulfill the purposes described in this policy.
        This is also the case for anyone that we share your information with and
        who carries out services on our behalf. When we no longer need to use
        your information and there is no need for us to keep it to comply with
        our legal or regulatory obligations, we’ll either remove it from our
        systems or depersonalize it so that we can&apos;t identify you.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
      <p className="mb-4">
        If you have any questions, don&apos;t hesitate to contact us via email:
        <a
          href="mailto:contact-us@lusiboientertainment.com"
          className="text-blue-600"
        >
          contact-us@lusiboientertainment.com
        </a>
      </p>
    </div>
  );
}

export default PrivacyPolicy;
